version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: editordb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "6033:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - db